services:
  - type: web
    name: inventory-management-api
    env: node
    region: oregon
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
